### ISSUE TITLE
大概什么时候会开源代码呢

### ISSUE THREAD

**Issue by guobabaya** [XuZhang1211/PVPUFormer#1]
你好，很想体验你们的技术，请问大概什么时候会分享代码和checkpoint呢。

**Comment by XuZhang1211** [comment]
We are currently organizing the code and will release the trained model weights soon. Please be patient and stay tuned.

**Comment by OSUANSDNC** [comment]
您好，我对这项工作很感兴趣，请问大概什么时候会分享代码
