### ISSUE TITLE
Amodal finetuning 

### ISSUE THREAD

**Issue by bhack** [XuZhang1211/PVPUFormer#2]
Do you will release some finetuning code/info?

I would like to experiment if this could be adapted/finetuned for amodal.

**Comment by XuZhang1211** [comment]
We do not plan to release the fine-tuning code for other datasets. To fine-tune for different scenarios, one can modify the data loader for adaptation and perform fine-tuning training based on the pre-trained model.

**Comment by bhack** [comment]
Ok let see the data loader when released.
